### ISSUE TITLE
Fix link to about page on login form

### ISSUE THREAD

**Issue by dhalladay** [Hone12345678/worthIt#40]
There is a link to the about page on the login form, however, current setup doesn't allow for the about page to render if the user isn't logged in. Should we add the About page to the forms that can render while logged out, or remove the link?

**Comment by dhalladay** [comment]
We should also conditionally render the nav links so they don't show up unless the user is logged in.

**Comment by RossWestwater** [comment]
this was done by someone. I dunno who. Closing.
